name: OBC
description: OBC Modelica App
hooks:
  - name: reheat-controller
    interval: 1
    controller: Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/Reheat/Controller.js
    parameters:
      VHeaMax_flow: 0.3
      VHeaMin_flow: 0.15
      VCooMax_flow: 1.5
      VOccMin_flow: 0.15